name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Make build.sh executable
        run: chmod +x ./build.sh
        
      - name: Run build script
        run: ./build.sh